name : Deploy to testing env dash tomboati
on:
  push:
    branches: [ main ]

jobs:
  first:
    name: Pull from github
    runs-on: ubuntu-latest
    steps:
    - name: deploy dev dash-tombo.bgskr-project.my.id
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USER }}
        key: ${{ secrets.MY_KEY }}
        port: ${{ secrets.PORT }}
        script: |
          cd ${{ secrets.DIR }}
          git pull origin main
